version: 2
updates:
    - package-ecosystem: "npm"
    directory: "/"
    schedule:
        interval: "daily"
    groups:
        dependencies:
            patterns:
                - "*"
    target:
        branches:
            - "main"
            - "dev"
            - "tailwind"
    labels:
        - "Dependabot"
