name: Review Dog
on: [pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: setup-node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - uses: pnpm/action-setup@v2
              with:
                  version: 8.5.1
            - run: pnpm i

            - uses: reviewdog/action-setup@v1
              with:
                reviewdog_version: latest
            - name: Run reviewdog
              env:
                REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: pnpm run lint | reviewdog -f=eslint -reporter=github-pr-review -filter-mode=diff_context -fail-on-error=true
