name: main
on:
    workflow_dispatch:
    push:
jobs:
    main:
        concurrency: main
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: setup-node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - run: pnpm install

    format:
        needs: [setup]
              uses: ./.github/workflows/format.yml

    lint:
        needs: [setup]
        uses: ./.github/workflows/lint.yml

    build-test:
        needs: [setup]
        uses: ./github/workflows/test-build.yml

    push:
        needs: [format, lint]
        uses: ./.github/workflows/push.yml

    discord:
        needs: [test-build, push]
        concurrency: last
        uses: ./.github/workflows/notice-discord.yml
