name: Build Test
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
          with:
            ref: ${{ github.head_ref }}

            - name: setup-node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: npm
            - run: |
                  npm ci
                  npm run lint

            - name: Build Next.js application
              run: |
                  touch .env.local          
                  echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env.local
                  echo "NEXT_PUBLIC_SUPABASE_PROJECT_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_PROJECT_URL }}" >> .env.local
                  echo "NEXT_PUBLIC_TURNSTILE_SITE_KEY"= ${{ secrets.NEXT_PUBLIC_TURNSTILE_SITE_KEY }} >> .env.local
                  npm run build

            - name: Actions Status Discord
              uses: sarisia/actions-status-discord@v1.12.0
              if: always()
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK }}
