name: Build Test
on:
  workflow_dispatch:
  pull_request_target:
      branches:
          - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            
            - name: setup-node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: npm
                  
            - name: run npm ci
              run: npm ci
            
            - name: Build Next.js application
              run: |
                  touch .env.local          
                  echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env.local
                  echo "NEXT_PUBLIC_SUPABASE_PROJECT_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_PROJECT_URL }}" >> .env.local
                  echo "NEXT_PUBLIC_TURNSTILE_SITE_KEY"= ${{ secrets.NEXT_PUBLIC_TURNSTILE_SITE_KEY }} >> .env.local
                  npm run build

            - name: Actions Status Discord
              uses: sarisia/actions-status-discord@v1.12.0
              if: always()
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK }}
