name: Build Test
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - dev
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Clean Install dependices
        run: rm -rf node_modules && npm ci

      - name: Lint code
        run: npm run lint

      - name: Build Next.js application
        run: npm run build
